version: '3.8'

services:
  fastapi_model:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8005:8005"
    volumes:
      - ./models:/app/models

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring:/etc/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
