#just for tac
statistics=true
job=master_Fact
jobVersion=0.1
date=2026-02-28 170315799
contextName=Default
jobId=_oEWAwBS9EfG_F644YAT1Fg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=PROJET_PI_BI
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=