#just for tac
statistics=true
job=Scout_DW_RUN_methode2
jobVersion=0.1
date=2026-02-28 170247041
contextName=Default
jobId=_89azwA9fEfGv_9o6Y0Uuqw
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=PROJET_PI_BI
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=