#just for tac
statistics=true
job=Scout_SA_RUN
jobVersion=0.1
date=2026-02-28 170138592
contextName=Default
jobId=_Uk3voAwSEfGbOtb91OpL1w
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=PROJET_PI_BI
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=